(server-mode)
(global-unset-key (kbd "M-m"))
(load-library "fc-package")
(load-library "fc-static-packages")
(load-library "fc-gui")
(load-library "fc-org")
(load-library "fc-findfile")
(load-library "fc-text")
(load-library "fc-navigate")
(load-library "fc-git")
(load-library "fc-snippets")
(load-library "fc-trash")
(load-library "fc-swiper")
(load-library "fc-projectile")
(load-library "fc-dired")
(load-library "fc-autocompletion")
(load-library "fc-help")
(load-library "fc-elmacro")
(load-library "fc-flycheck")

(load-library "fc-elixir")
(load-library "fc-erlang")
(load-library "fc-php")
(load-library "fc-javascript")
(load-library "fc-textfiles")
(load-library "fc-web")
(load-library "fc-typescript")
(load-library "fc-markdown")
(load-library "fc-rest")
(load-library "fc-docker")
(load-library "fc-go")
(load-library "fc-rust")
(load-library "fc-elisp")
(load-library "fc-dart")
(load-library "fc-elm")

(load-library "fc-keys")
(load-library "fc-settings")
